"""initial migration

Revision ID: eff740494a1c
Revises: 
Create Date: 2025-07-31 13:11:29.054070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff740494a1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stars', sa.Enum('um', 'dois', 'tres', 'quatro', 'cinco', name='starrating'), nullable=False),
    sa.Column('subject_type', sa.Enum('biologia', 'quimica', 'fisica', 'matematica', 'historia', 'geografia', 'sociologia', 'filosofia', 'linguagens', 'literatura', name='subjectsenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    # ### end Alembic commands ###
